### ISSUE TITLE
How to use  blockchain-dev-tools?

### ISSUE THREAD

**Issue by dedetuga** [JBaczuk/blockchain-dev-tools#3]
Hi,
I'm following you tutorial [how to fork bitcoin part-2](https://medium.com/@jordan.baczuk/how-to-fork-bitcoin-part-2-59b9eddb49a4) and when i get on Genesis block and Mining the genesis block everything fall apart i start to get error in `hashGenesisBlock` and `hashMerkleRoot`
`learncoind: chainparams.cpp:233: CTestNetParams::CTestNetParams(): Assertion consensus.hashGenesisBlock == uint256S("0x000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943") failed.
Aborted (core dumped)
`
 when i run `./learncoind ...`
I tthink im missing something.
Can you help?

**Comment by JBaczuk** [comment]
Can you share your GitHub repo?

**Comment by dedetuga** [comment]
I used this one as suggested on tutorial [BTC 0.17.1](https://github.com/bitcoin/bitcoin/tree/v0.17.1)

**Comment by dedetuga** [comment]
I Find your [learncoin repo](url) i will follow it. thanks
